export const assets = [
  {
    id: 1,
    name: 'Workstation - John Doe',
    type: 'Computer',
    description: 'Dell XPS Desktop assigned to John Doe',
    model: 'XPS 8940',
    serialNumber: '123456-7890-ABCD',
    location: 'Building A, Floor 3, Cubicle 12',
    purchaseDate: '2023-10-26',
    warranty: {
      startDate: '2023-10-26',
      endDate: '2025-10-25',
    },
    status: 'Active',
  },
  {
    id: 2,
    name: 'Network Switch',
    type: 'Networking',
    description: 'Cisco Catalyst 2960-X Series Switch',
    model: 'WS-C2960X-48TS-PDL',
    serialNumber: 'ABCDEF-1234-5678',
    location: 'Server Room',
    purchaseDate: '2022-05-12',
    warranty: {
      startDate: '2022-05-12',
      endDate: '2024-05-11',
    },
    status: 'Active',
  },
  {
    id: 3,
    name: 'Software License - Adobe Creative Suite',
    type: 'License',
    description: 'Adobe Creative Suite subscription for design team',
    version: '2023',
    licenseKey: 'XXXXXX-YYYYYY-ZZZZZZ',
    assignedTo: 'Design Team',
    renewalDate: '2024-07-14',
    status: 'Active',
  },
  {
    id: 4,
    name: 'Conference Table',
    type: 'Furniture',
    description: 'Large rectangular table for conference room',
    model: 'NA',
    serialNumber: 'N/A',
    location: 'Conference Room 1',
    purchaseDate: '2020-08-01',
    warranty: {
      startDate: '2020-08-01',
      endDate: 'N/A',
    },
    status: 'Active',
  },
  {
    id: 5,
    name: 'Printer - LaserJet Pro M404dn',
    type: 'Office Equipment',
    description: 'HP LaserJet Pro multifunction printer',
    model: 'M404dn',
    serialNumber: '7890-FEDC-3210',
    location: 'Break Room - Printing Station',
    purchaseDate: '2023-02-14',
    warranty: {
      startDate: '2023-02-14',
      endDate: '2025-02-13',
    },
    status: 'Active',
  },
  {
    id: 6,
    name: 'Projector',
    type: 'AV Equipment',
    description: 'Basic projector for conference room',
    model: 'Optoma EX3240',
    serialNumber: '987654-3210-FEDC',
    location: 'Conference Room 2',
    purchaseDate: '2021-04-21',
    warranty: {
      startDate: '2021-04-21',
      endDate: '2023-04-20',
    },
    status: 'In Repair',
  },

  {
    id: 7,
    name: 'Laptop - Dell XPS 13',
    type: 'Computer',
    description: 'Assigned to Sarah Lee',
    model: 'XPS 13',
    serialNumber: 'CBA987-654321-FED',
    location: 'Sarah Lee - Desk',
    purchaseDate: '2022-06-22',
    warranty: {
      startDate: '2022-06-22',
      endDate: '2024-06-21',
    },
    status: 'Active',
  },
  {
    id: 8,
    name: 'Chair - Ergonomic',
    type: 'Furniture',
    description: 'Ergonomic office chair for back support',
    model: 'NA',
    serialNumber: 'N/A',
    location: 'Building B, Floor 2, Cubicle 5',
    purchaseDate: '2023-01-17',
    warranty: {
      startDate: '2023-01-17',
      endDate: '2025-01-16',
    },
    status: 'Active',
  },
  {
    id: 9,
    name: 'Software License - Microsoft Office 365',
    type: 'License',
    description: 'Subscription for office productivity software',
    version: 'Business Standard',
    licenseKey: 'N/A',
    assignedTo: 'All Employees',
    renewalDate: '2024-10-26',
    status: 'Active',
  },
  {
    id: 10,
    name: 'Headset - Wireless',
    type: 'Office Equipment',
    description: 'Wireless headset for calls and video conferencing',
    model: 'Jabra Evolve 75',
    serialNumber: '4321-0FED-CBA9',
    location: 'Marketing Department',
    purchaseDate: '2023-11-09',
    warranty: {
      startDate: '2023-11-09',
      endDate: '2025-11-08',
    },
    status: 'Active',
  },
  {
    id: 11,
    name: 'Server - Database',
    type: 'Hardware',
    description: 'High-performance server for storing company data',
    model: 'HP ProLiant DL360 Gen10',
    serialNumber: 'FEDC3210-9876-5432',
    location: 'Server Room',
    purchaseDate: '2022-09-08',
    warranty: {
      startDate: '2022-09-08',
      endDate: '2024-09-07',
    },
    status: 'Active',
  },
  {
    id: 12,
    name: 'Tablet - Samsung Galaxy Tab S8',
    type: 'Mobile Device',
    description: 'Assigned to field sales representative',
    model: 'Galaxy Tab S8',
    serialNumber: 'ZXCV987-FEDCBA-5432',
    location: 'David Jones - Field Sales',
    purchaseDate: '2024-02-14',
    warranty: {
      startDate: '2024-02-14',
      endDate: '2026-02-13',
    },
    status: 'Active',
  },
  {
    id: 13,
    name: 'Security Camera System',
    type: 'Security Equipment',
    description: '4-camera system for monitoring office building',
    model: 'NA',
    serialNumber: 'N/A',
    location: 'Building Perimeter & Entrances',
    purchaseDate: '2021-05-12',
    warranty: {
      startDate: '2021-05-12',
      endDate: '2023-05-11',
    },
    status: 'Needs Maintenance',
  },
  {
    id: 14,
    name: 'Whiteboard',
    type: 'Office Supplies',
    description: 'Large whiteboard for brainstorming sessions',
    model: 'NA',
    serialNumber: 'N/A',
    location: 'Conference Room 1',
    purchaseDate: '2020-12-01',
    warranty: {
      startDate: 'N/A',
      endDate: 'N/A',
    },
    status: 'Active',
  },
  {
    id: 15,
    name: 'USB Drive - 128GB',
    type: 'Storage Device',
    description: 'For data transfer and backup',
    model: 'SanDisk Cruzer Fit',
    serialNumber: '123ABC-456DEF',
    location: 'IT Department - Storage',
    purchaseDate: '2024-01-10',
    warranty: {
      startDate: '2024-01-10',
      endDate: '2026-01-09',
    },
    status: 'Active',
  },
  {
    id: 16,
    name: 'Software License - Antivirus',
    type: 'License',
    description: 'Company-wide antivirus protection',
    version: '2024',
    licenseKey: 'N/A',
    assignedTo: 'All Employees',
    renewalDate: '2025-03-15',
    status: 'Active',
  },
  {
    id: 17,
    name: 'Tool Kit - Basic',
    type: 'Office Supplies',
    description: 'Set of common tools for maintenance tasks',
    model: 'NA',
    serialNumber: 'N/A',
    location: 'Facilities Department',
    purchaseDate: '2023-08-21',
    warranty: {
      startDate: 'N/A',
      endDate: 'N/A',
    },
    status: 'Active',
  },
  {
    id: 18,
    name: 'Router',
    type: 'Networking',
    description: 'Provides internet access for the office network',
    model: 'Linksys Velop WHW3203',
    serialNumber: '7890-CBA9-FEDC',
    location: 'IT Department - Network Rack',
    purchaseDate: '2022-02-07',
    warranty: {
      startDate: '2022-02-07',
      endDate: '2024-02-06',
    },
    status: 'Active',
  },
  {
    id: 19,
    name: 'Fire Extinguisher',
    type: 'Safety Equipment',
    description: 'Wall-mounted fire extinguisher for fire safety',
    model: 'ABC Dry Chemical',
    serialNumber: '5432-FEDC-1234',
    location: 'Building B, Hallway near Exit',
    purchaseDate: '2021-01-19',
    warranty: {
      startDate: 'N/A',
      endDate: '2026-01-18',
    },
    status: 'Active',
  },
  {
    id: 20,
    name: 'Coffee Machine',
    type: 'Office Equipment',
    description: 'Brews coffee for employee refreshment',
    model: 'Keurig K-Supreme Plus Smart',
    serialNumber: '3210-FEDC-9876',
    location: 'Break Room - Kitchen Area',
    purchaseDate: '2023-05-18',
    warranty: {
      startDate: '2023-05-18',
      endDate: '2025-05-17',
    },
    status: 'Active',
  },
  {
    id: 21,
    name: 'Desk Lamp',
    type: 'Office Supplies',
    description: 'Adjustable desk lamp for better task lighting',
    model: 'NA',
    serialNumber: 'N/A',
    location: 'Building A, Floor 3, Cubicle 12',
    purchaseDate: '2022-10-26',
    warranty: {
      startDate: 'N/A',
      endDate: 'N/A',
    },
    status: 'Active',
  },
  {
    id: 22,
    name: 'First Aid Kit',
    type: 'Safety Equipment',
    description: 'Basic medical supplies for minor workplace injuries',
    model: 'NA',
    serialNumber: 'N/A',
    location: 'Multiple Locations (Restocked Regularly)',
    purchaseDate: '2024-02-10',
    warranty: {
      startDate: 'N/A',
      endDate: 'N/A',
    },
    status: 'Active',
  },
  {
    id: 23,
    name: 'VoIP Phone System',
    type: 'Telecommunications',
    description: 'Provides business phone functionality over the internet',
    model: 'Cisco Business Phones 3300 Series',
    serialNumber: 'N/A',
    location: 'Company-Wide',
    purchaseDate: '2020-07-14',
    warranty: {
      startDate: '2020-07-14',
      endDate: '2023-07-13',
    },
    status: 'Needs Upgrade',
  },
  {
    id: 24,
    name: 'Software - Design Software',
    type: 'License',
    description: 'Suite of creative design software for graphics team',
    version: '2024',
    licenseKey: 'N/A',
    assignedTo: 'Graphics Team',
    renewalDate: '2024-08-12',
    status: 'Active',
  },
  {
    id: 25,
    name: 'Website Domain',
    type: 'License',
    description: 'Domain name for the company website',
    version: 'N/A',
    licenseKey: 'N/A',
    assignedTo: 'IT Department',
    renewalDate: '2024-11-21',
    status: 'Active',
  },
  {
    id: 26,
    name: 'Scanner',
    type: 'Office Equipment',
    description: 'Multifunction device for scanning documents',
    model: 'Brother MFC-L3770DW',
    serialNumber: '9876-FEDC-3210',
    location: 'Finance Department',
    purchaseDate: '2022-04-12',
    warranty: {
      startDate: '2022-04-12',
      endDate: '2024-04-11',
    },
    status: 'Active',
  },
  {
    id: 27,
    name: 'Chair Mat',
    type: 'Office Supplies',
    description: 'Protects floor from office chair wear and tear',
    model: 'NA',
    serialNumber: 'N/A',
    location: 'Building B, Floor 1 - Various cubicles',
    purchaseDate: '2023-09-22',
    warranty: {
      startDate: 'N/A',
      endDate: 'N/A',
    },
    status: 'Active',
  },
  {
    id: 28,
    name: 'External Hard Drive',
    type: 'Storage Device',
    description: 'For data backup and storage',
    model: 'Seagate Backup Plus Portable 5TB',
    serialNumber: '123ABC-456DEF-7890',
    location: 'IT Department - Storage',
    purchaseDate: '2024-01-05',
    warranty: {
      startDate: '2024-01-05',
      endDate: '2026-01-04',
    },
    status: 'Active',
  },
  {
    id: 29,
    name: 'Software - Project Management',
    type: 'License',
    description: 'Project management software for team collaboration',
    version: 'Enterprise',
    licenseKey: 'N/A',
    assignedTo: 'Project Management Team',
    renewalDate: '2025-02-14',
    status: 'Active',
  },
  {
    id: 30,
    name: '3D Printer',
    type: 'Hardware',
    description: 'Used for prototyping and creating physical models',
    model: 'Creality Ender 3 V2',
    serialNumber: 'FEDC3210-5432-1234',
    location: 'Engineering Department',
    purchaseDate: '2023-12-07',
    warranty: {
      startDate: '2023-12-07',
      endDate: '2025-12-06',
    },
    status: 'Active',
  },
];
