export const assets = [
  {
    id: 1,
    name: 'Workstation - John Doe',
    type: 'Computer',
    description: 'Dell XPS Desktop assigned to John Doe',
    model: 'XPS 8940',
    serialNumber: '123456-7890-ABCD',
    location: 'Building A, Floor 3, Cubicle 12',
    purchaseDate: '2023-10-26',
    warranty: {
      startDate: '2023-10-26',
      endDate: '2025-10-25',
    },
    status: 'Active',
  },
  {
    id: 2,
    name: 'Network Switch',
    type: 'Networking',
    description: 'Cisco Catalyst 2960-X Series Switch',
    model: 'WS-C2960X-48TS-PDL',
    serialNumber: 'ABCDEF-1234-5678',
    location: 'Server Room',
    purchaseDate: '2022-05-12',
    warranty: {
      startDate: '2022-05-12',
      endDate: '2024-05-11',
    },
    status: 'Active',
  },
  {
    id: 3,
    name: 'Software License - Adobe Creative Suite',
    type: 'License',
    description: 'Adobe Creative Suite subscription for design team',
    version: '2023',
    licenseKey: 'XXXXXX-YYYYYY-ZZZZZZ',
    assignedTo: 'Design Team',
    renewalDate: '2024-07-14',
    status: 'Active',
  },
  {
    id: 4,
    name: 'Conference Table',
    type: 'Furniture',
    description: 'Large rectangular table for conference room',
    model: 'NA',
    serialNumber: 'N/A',
    location: 'Conference Room 1',
    purchaseDate: '2020-08-01',
    warranty: {
      startDate: '2020-08-01',
      endDate: 'N/A',
    },
    status: 'Active',
  },
  {
    id: 5,
    name: 'Printer - LaserJet Pro M404dn',
    type: 'Office Equipment',
    description: 'HP LaserJet Pro multifunction printer',
    model: 'M404dn',
    serialNumber: '7890-FEDC-3210',
    location: 'Break Room - Printing Station',
    purchaseDate: '2023-02-14',
    warranty: {
      startDate: '2023-02-14',
      endDate: '2025-02-13',
    },
    status: 'Active',
  },
  {
    id: 6,
    name: 'Projector',
    type: 'AV Equipment',
    description: 'Basic projector for conference room',
    model: 'Optoma EX3240',
    serialNumber: '987654-3210-FEDC',
    location: 'Conference Room 2',
    purchaseDate: '2021-04-21',
    warranty: {
      startDate: '2021-04-21',
      endDate: '2023-04-20',
    },
    status: 'In Repair',
  },

  {
    id: 7,
    name: 'Laptop - Dell XPS 13',
    type: 'Computer',
    description: 'Assigned to Sarah Lee',
    model: 'XPS 13',
    serialNumber: 'CBA987-654321-FED',
    location: 'Sarah Lee - Desk',
    purchaseDate: '2022-06-22',
    warranty: {
      startDate: '2022-06-22',
      endDate: '2024-06-21',
    },
    status: 'Active',
  },
  {
    id: 8,
    name: 'Chair - Ergonomic',
    type: 'Furniture',
    description: 'Ergonomic office chair for back support',
    model: 'NA',
    serialNumber: 'N/A',
    location: 'Building B, Floor 2, Cubicle 5',
    purchaseDate: '2023-01-17',
    warranty: {
      startDate: '2023-01-17',
      endDate: '2025-01-16',
    },
    status: 'Active',
  },
  {
    id: 9,
    name: 'Software License - Microsoft Office 365',
    type: 'License',
    description: 'Subscription for office productivity software',
    version: 'Business Standard',
    licenseKey: 'N/A',
    assignedTo: 'All Employees',
    renewalDate: '2024-10-26',
    status: 'Active',
  },
  {
    id: 10,
    name: 'Headset - Wireless',
    type: 'Office Equipment',
    description: 'Wireless headset for calls and video conferencing',
    model: 'Jabra Evolve 75',
    serialNumber: '4321-0FED-CBA9',
    location: 'Marketing Department',
    purchaseDate: '2023-11-09',
    warranty: {
      startDate: '2023-11-09',
      endDate: '2025-11-08',
    },
    status: 'Active',
  },
  {
    id: 11,
    name: 'Server - Database',
    type: 'Hardware',
    description: 'High-performance server for storing company data',
    model: 'HP ProLiant DL360 Gen10',
    serialNumber: 'FEDC3210-9876-5432',
    location: 'Server Room',
    purchaseDate: '2022-09-08',
    warranty: {
      startDate: '2022-09-08',
      endDate: '2024-09-07',
    },
    status: 'Active',
  },
  {
    id: 12,
    name: 'Tablet - Samsung Galaxy Tab S8',
    type: 'Mobile Device',
    description: 'Assigned to field sales representative',
    model: 'Galaxy Tab S8',
    serialNumber: 'ZXCV987-FEDCBA-5432',
    location: 'David Jones - Field Sales',
    purchaseDate: '2024-02-14',
    warranty: {
      startDate: '2024-02-14',
      endDate: '2026-02-13',
    },
    status: 'Active',
  },
  {
    id: 13,
    name: 'Security Camera System',
    type: 'Security Equipment',
    description: '4-camera system for monitoring office building',
    model: 'NA',
    serialNumber: 'N/A',
    location: 'Building Perimeter & Entrances',
    purchaseDate: '2021-05-12',
    warranty: {
      startDate: '2021-05-12',
      endDate: '2023-05-11',
    },
    status: 'Needs Maintenance',
  },
  {
    id: 14,
    name: 'Whiteboard',
    type: 'Office Supplies',
    description: 'Large whiteboard for brainstorming sessions',
    model: 'NA',
    serialNumber: 'N/A',
    location: 'Conference Room 1',
    purchaseDate: '2020-12-01',
    warranty: {
      startDate: 'N/A',
      endDate: 'N/A',
    },
    status: 'Active',
  },
  {
    id: 15,
    name: 'USB Drive - 128GB',
    type: 'Storage Device',
    description: 'For data transfer and backup',
    model: 'SanDisk Cruzer Fit',
    serialNumber: '123ABC-456DEF',
    location: 'IT Department - Storage',
    purchaseDate: '2024-01-10',
    warranty: {
      startDate: '2024-01-10',
      endDate: '2026-01-09',
    },
    status: 'Active',
  },
  {
    id: 16,
    name: 'Software License - Antivirus',
    type: 'License',
    description: 'Company-wide antivirus protection',
    version: '2024',
    licenseKey: 'N/A',
    assignedTo: 'All Employees',
    renewalDate: '2025-03-15',
    status: 'Active',
  },
  {
    id: 17,
    name: 'Tool Kit - Basic',
    type: 'Office Supplies',
    description: 'Set of common tools for maintenance tasks',
    model: 'NA',
    serialNumber: 'N/A',
    location: 'Facilities Department',
    purchaseDate: '2023-08-21',
    warranty: {
      startDate: 'N/A',
      endDate: 'N/A',
    },
    status: 'Active',
  },
  {
    id: 18,
    name: 'Router',
    type: 'Networking',
    description: 'Provides internet access for the office network',
    model: 'Linksys Velop WHW3203',
    serialNumber: '7890-CBA9-FEDC',
    location: 'IT Department - Network Rack',
    purchaseDate: '2022-02-07',
    warranty: {
      startDate: '2022-02-07',
      endDate: '2024-02-06',
    },
    status: 'Active',
  },
  {
    id: 19,
    name: 'Fire Extinguisher',
    type: 'Safety Equipment',
    description: 'Wall-mounted fire extinguisher for fire safety',
    model: 'ABC Dry Chemical',
    serialNumber: '5432-FEDC-1234',
    location: 'Building B, Hallway near Exit',
    purchaseDate: '2021-01-19',
    warranty: {
      startDate: 'N/A',
      endDate: '2026-01-18',
    },
    status: 'Active',
  },
  {
    id: 20,
    name: 'Coffee Machine',
    type: 'Office Equipment',
    description: 'Brews coffee for employee refreshment',
    model: 'Keurig K-Supreme Plus Smart',
    serialNumber: '3210-FEDC-9876',
    location: 'Break Room - Kitchen Area',
    purchaseDate: '2023-05-18',
    warranty: {
      startDate: '2023-05-18',
      endDate: '2025-05-17',
    },
    status: 'Active',
  },
  {
    id: 21,
    name: 'Desk Lamp',
    type: 'Office Supplies',
    description: 'Adjustable desk lamp for better task lighting',
    model: 'NA',
    serialNumber: 'N/A',
    location: 'Building A, Floor 3, Cubicle 12',
    purchaseDate: '2022-10-26',
    warranty: {
      startDate: 'N/A',
      endDate: 'N/A',
    },
    status: 'Active',
  },
  {
    id: 22,
    name: 'First Aid Kit',
    type: 'Safety Equipment',
    description: 'Basic medical supplies for minor workplace injuries',
    model: 'NA',
    serialNumber: 'N/A',
    location: 'Multiple Locations (Restocked Regularly)',
    purchaseDate: '2024-02-10',
    warranty: {
      startDate: 'N/A',
      endDate: 'N/A',
    },
    status: 'Active',
  },
  {
    id: 23,
    name: 'VoIP Phone System',
    type: 'Telecommunications',
    description: 'Provides business phone functionality over the internet',
    model: 'Cisco Business Phones 3300 Series',
    serialNumber: 'N/A',
    location: 'Company-Wide',
    purchaseDate: '2020-07-14',
    warranty: {
      startDate: '2020-07-14',
      endDate: '2023-07-13',
    },
    status: 'Needs Upgrade',
  },
  {
    id: 24,
    name: 'Software - Design Software',
    type: 'License',
    description: 'Suite of creative design software for graphics team',
    version: '2024',
    licenseKey: 'N/A',
    assignedTo: 'Graphics Team',
    renewalDate: '2024-08-12',
    status: 'Active',
  },
  {
    id: 25,
    name: 'Website Domain',
    type: 'License',
    description: 'Domain name for the company website',
    version: 'N/A',
    licenseKey: 'N/A',
    assignedTo: 'IT Department',
    renewalDate: '2024-11-21',
    status: 'Active',
  },
  {
    id: 26,
    name: 'Scanner',
    type: 'Office Equipment',
    description: 'Multifunction device for scanning documents',
    model: 'Brother MFC-L3770DW',
    serialNumber: '9876-FEDC-3210',
    location: 'Finance Department',
    purchaseDate: '2022-04-12',
    warranty: {
      startDate: '2022-04-12',
      endDate: '2024-04-11',
    },
    status: 'Active',
  },
  {
    id: 27,
    name: 'Chair Mat',
    type: 'Office Supplies',
    description: 'Protects floor from office chair wear and tear',
    model: 'NA',
    serialNumber: 'N/A',
    location: 'Building B, Floor 1 - Various cubicles',
    purchaseDate: '2023-09-22',
    warranty: {
      startDate: 'N/A',
      endDate: 'N/A',
    },
    status: 'Active',
  },
  {
    id: 28,
    name: 'External Hard Drive',
    type: 'Storage Device',
    description: 'For data backup and storage',
    model: 'Seagate Backup Plus Portable 5TB',
    serialNumber: '123ABC-456DEF-7890',
    location: 'IT Department - Storage',
    purchaseDate: '2024-01-05',
    warranty: {
      startDate: '2024-01-05',
      endDate: '2026-01-04',
    },
    status: 'Active',
  },
  {
    id: 29,
    name: 'Software - Project Management',
    type: 'License',
    description: 'Project management software for team collaboration',
    version: 'Enterprise',
    licenseKey: 'N/A',
    assignedTo: 'Project Management Team',
    renewalDate: '2025-02-14',
    status: 'Active',
  },
  {
    id: 30,
    name: '3D Printer',
    type: 'Hardware',
    description: 'Used for prototyping and creating physical models',
    model: 'Creality Ender 3 V2',
    serialNumber: 'FEDC3210-5432-1234',
    location: 'Engineering Department',
    purchaseDate: '2023-12-07',
    warranty: {
      startDate: '2023-12-07',
      endDate: '2025-12-06',
    },
    status: 'Active',
  },
];

export const locationsWithAssets: {[key: string]: object[]} = {
  'Building A, Floor 3, Cubicle 12': [
    {
      id: 1,
      name: 'Workstation - John Doe',
      type: 'Computer',
      description: 'Dell XPS Desktop assigned to John Doe',
      model: 'XPS 8940',
      serialNumber: '123456-7890-ABCD',
      location: 'Building A, Floor 3, Cubicle 12',
      purchaseDate: '2023-10-26',
      warranty: {
        startDate: '2023-10-26',
        endDate: '2025-10-25',
      },
      status: 'Active',
    },
    {
      id: 21,
      name: 'Desk Lamp',
      type: 'Office Supplies',
      description: 'Adjustable desk lamp for better task lighting',
      model: 'NA',
      serialNumber: 'N/A',
      location: 'Building A, Floor 3, Cubicle 12',
      purchaseDate: '2022-10-26',
      warranty: {
        startDate: 'N/A',
        endDate: 'N/A',
      },
      status: 'Active',
    },
  ],
  'Server Room': [
    {
      id: 2,
      name: 'Network Switch',
      type: 'Networking',
      description: 'Cisco Catalyst 2960-X Series Switch',
      model: 'WS-C2960X-48TS-PDL',
      serialNumber: 'ABCDEF-1234-5678',
      location: 'Server Room',
      purchaseDate: '2022-05-12',
      warranty: {
        startDate: '2022-05-12',
        endDate: '2024-05-11',
      },
      status: 'Active',
    },
    {
      id: 11,
      name: 'Server - Database',
      type: 'Hardware',
      description: 'High-performance server for storing company data',
      model: 'HP ProLiant DL360 Gen10',
      serialNumber: 'FEDC3210-9876-5432',
      location: 'Server Room',
      purchaseDate: '2022-09-08',
      warranty: {
        startDate: '2022-09-08',
        endDate: '2024-09-07',
      },
      status: 'Active',
    },
    {
      id: 61,
      name: 'Server (Web Hosting)',
      type: 'Computer',
      description: 'Server dedicated to hosting the company website',
      model: 'Dell PowerEdge R6520',
      serialNumber: 'ABCDEF-012345-67890',
      locationId: 2,
      purchaseDate: '2022-06-07',
      warranty: {
        startDate: '2022-06-07',
        endDate: '2024-06-06',
      },
      status: 'Active',
    },
    {
      id: 62,
      name: 'Network Switch (Core)',
      type: 'Networking',
      description: 'Main switch for routing network traffic within the company',
      model: 'Cisco Catalyst 9300',
      serialNumber: 'FEDC3210-5432-1234',
      locationId: 2,
      purchaseDate: '2023-09-29',
      warranty: {
        startDate: '2023-09-29',
        endDate: '2025-09-28',
      },
      status: 'Active',
    },
    {
      id: 63,
      name: 'Uninterruptible Power Supply (UPS)',
      type: 'Power Supply',
      description: 'Provides backup power to servers in case of power outage',
      model: 'APC Smart-UPS C 3000',
      serialNumber: '12345-67890-FEDC',
      locationId: 2,
      purchaseDate: '2021-05-18',
      warranty: {
        startDate: '2021-05-18',
        endDate: '2024-05-17',
      },
      status: 'Needs Maintenance',
    },
    {
      id: 64,
      name: 'Server Monitoring Software',
      type: 'License',
      description: 'Software for monitoring server performance and health',
      version: 'Enterprise',
      licenseKey: 'N/A',
      assignedTo: 'IT Department',
      renewalDate: '2025-02-10',
      status: 'Active',
    },
    {
      id: 65,
      name: 'Server Racks',
      type: 'Hardware',
      description: 'Cabinet for housing and organizing multiple servers',
      model: 'NA',
      serialNumber: 'NA',
      locationId: 2,
      purchaseDate: '2020-12-02',
      warranty: {
        startDate: 'N/A',
        endDate: 'N/A',
      },
      status: 'Active',
    },
    {
      id: 66,
      name: 'Fire Suppression System',
      type: 'Safety Equipment',
      description: 'System for extinguishing fires within the server room',
      model: 'NA',
      serialNumber: 'NA',
      locationId: 2,
      purchaseDate: '2022-06-07',
      warranty: {
        startDate: '2022-06-07',
        endDate: '2027-06-06',
      },
      status: 'Active',
    },
  ],
  'undefined': [
    {
      id: 3,
      name: 'Software License - Adobe Creative Suite',
      type: 'License',
      description: 'Adobe Creative Suite subscription for design team',
      version: '2023',
      licenseKey: 'XXXXXX-YYYYYY-ZZZZZZ',
      assignedTo: 'Design Team',
      renewalDate: '2024-07-14',
      status: 'Active',
    },
    {
      id: 9,
      name: 'Software License - Microsoft Office 365',
      type: 'License',
      description: 'Subscription for office productivity software',
      version: 'Business Standard',
      licenseKey: 'N/A',
      assignedTo: 'All Employees',
      renewalDate: '2024-10-26',
      status: 'Active',
    },
    {
      id: 16,
      name: 'Software License - Antivirus',
      type: 'License',
      description: 'Company-wide antivirus protection',
      version: '2024',
      licenseKey: 'N/A',
      assignedTo: 'All Employees',
      renewalDate: '2025-03-15',
      status: 'Active',
    },
    {
      id: 24,
      name: 'Software - Design Software',
      type: 'License',
      description: 'Suite of creative design software for graphics team',
      version: '2024',
      licenseKey: 'N/A',
      assignedTo: 'Graphics Team',
      renewalDate: '2024-08-12',
      status: 'Active',
    },
    {
      id: 25,
      name: 'Website Domain',
      type: 'License',
      description: 'Domain name for the company website',
      version: 'N/A',
      licenseKey: 'N/A',
      assignedTo: 'IT Department',
      renewalDate: '2024-11-21',
      status: 'Active',
    },
    {
      id: 29,
      name: 'Software - Project Management',
      type: 'License',
      description: 'Project management software for team collaboration',
      version: 'Enterprise',
      licenseKey: 'N/A',
      assignedTo: 'Project Management Team',
      renewalDate: '2025-02-14',
      status: 'Active',
    },
  ],
  'Conference Room 1': [
    {
      id: 4,
      name: 'Conference Table',
      type: 'Furniture',
      description: 'Large rectangular table for conference room',
      model: 'NA',
      serialNumber: 'N/A',
      location: 'Conference Room 1',
      purchaseDate: '2020-08-01',
      warranty: {
        startDate: '2020-08-01',
        endDate: 'N/A',
      },
      status: 'Active',
    },
    {
      id: 14,
      name: 'Whiteboard',
      type: 'Office Supplies',
      description: 'Large whiteboard for brainstorming sessions',
      model: 'NA',
      serialNumber: 'N/A',
      location: 'Conference Room 1',
      purchaseDate: '2020-12-01',
      warranty: {
        startDate: 'N/A',
        endDate: 'N/A',
      },
      status: 'Active',
    },
  ],
  'Break Room - Printing Station': [
    {
      id: 5,
      name: 'Printer - LaserJet Pro M404dn',
      type: 'Office Equipment',
      description: 'HP LaserJet Pro multifunction printer',
      model: 'M404dn',
      serialNumber: '7890-FEDC-3210',
      location: 'Break Room - Printing Station',
      purchaseDate: '2023-02-14',
      warranty: {
        startDate: '2023-02-14',
        endDate: '2025-02-13',
      },
      status: 'Active',
    },
  ],
  'Conference Room 2': [
    {
      id: 6,
      name: 'Projector',
      type: 'AV Equipment',
      description: 'Basic projector for conference room',
      model: 'Optoma EX3240',
      serialNumber: '987654-3210-FEDC',
      location: 'Conference Room 2',
      purchaseDate: '2021-04-21',
      warranty: {
        startDate: '2021-04-21',
        endDate: '2023-04-20',
      },
      status: 'In Repair',
    },
  ],
  'Sarah Lee - Desk': [
    {
      id: 7,
      name: 'Laptop - Dell XPS 13',
      type: 'Computer',
      description: 'Assigned to Sarah Lee',
      model: 'XPS 13',
      serialNumber: 'CBA987-654321-FED',
      location: 'Sarah Lee - Desk',
      purchaseDate: '2022-06-22',
      warranty: {
        startDate: '2022-06-22',
        endDate: '2024-06-21',
      },
      status: 'Active',
    },
  ],
  'Building B, Floor 2, Cubicle 5': [
    {
      id: 8,
      name: 'Chair - Ergonomic',
      type: 'Furniture',
      description: 'Ergonomic office chair for back support',
      model: 'NA',
      serialNumber: 'N/A',
      location: 'Building B, Floor 2, Cubicle 5',
      purchaseDate: '2023-01-17',
      warranty: {
        startDate: '2023-01-17',
        endDate: '2025-01-16',
      },
      status: 'Active',
    },
  ],
  'Marketing Department': [
    {
      id: 10,
      name: 'Headset - Wireless',
      type: 'Office Equipment',
      description: 'Wireless headset for calls and video conferencing',
      model: 'Jabra Evolve 75',
      serialNumber: '4321-0FED-CBA9',
      location: 'Marketing Department',
      purchaseDate: '2023-11-09',
      warranty: {
        startDate: '2023-11-09',
        endDate: '2025-11-08',
      },
      status: 'Active',
    },
  ],
  'David Jones - Field Sales': [
    {
      id: 12,
      name: 'Tablet - Samsung Galaxy Tab S8',
      type: 'Mobile Device',
      description: 'Assigned to field sales representative',
      model: 'Galaxy Tab S8',
      serialNumber: 'ZXCV987-FEDCBA-5432',
      location: 'David Jones - Field Sales',
      purchaseDate: '2024-02-14',
      warranty: {
        startDate: '2024-02-14',
        endDate: '2026-02-13',
      },
      status: 'Active',
    },
  ],
  'Building Perimeter & Entrances': [
    {
      id: 13,
      name: 'Security Camera System',
      type: 'Security Equipment',
      description: '4-camera system for monitoring office building',
      model: 'NA',
      serialNumber: 'N/A',
      location: 'Building Perimeter & Entrances',
      purchaseDate: '2021-05-12',
      warranty: {
        startDate: '2021-05-12',
        endDate: '2023-05-11',
      },
      status: 'Needs Maintenance',
    },
  ],
  'IT Department - Storage': [
    {
      id: 15,
      name: 'USB Drive - 128GB',
      type: 'Storage Device',
      description: 'For data transfer and backup',
      model: 'SanDisk Cruzer Fit',
      serialNumber: '123ABC-456DEF',
      location: 'IT Department - Storage',
      purchaseDate: '2024-01-10',
      warranty: {
        startDate: '2024-01-10',
        endDate: '2026-01-09',
      },
      status: 'Active',
    },
    {
      id: 28,
      name: 'External Hard Drive',
      type: 'Storage Device',
      description: 'For data backup and storage',
      model: 'Seagate Backup Plus Portable 5TB',
      serialNumber: '123ABC-456DEF-7890',
      location: 'IT Department - Storage',
      purchaseDate: '2024-01-05',
      warranty: {
        startDate: '2024-01-05',
        endDate: '2026-01-04',
      },
      status: 'Active',
    },
    {
      id: 31,
      name: 'Network Attached Storage (NAS)',
      type: 'Storage Device',
      description: 'High-capacity device for storing network data',
      model: 'Synology DS1821+',
      serialNumber: 'ABCDEF-012345-67890',
      locationId: 10,
      purchaseDate: '2022-06-15',
      warranty: {
        startDate: '2022-06-15',
        endDate: '2024-06-14',
      },
      status: 'Active',
    },
    {
      id: 32,
      name: 'Backup Tapes',
      type: 'Storage Media',
      description: 'Set of magnetic tapes for data backups',
      model: 'LTO-8',
      serialNumber: 'N/A',
      locationId: 10,
      purchaseDate: '2024-02-22',
      warranty: {
        startDate: 'N/A',
        endDate: 'N/A',
      },
      status: 'Active',
    },
    {
      id: 33,
      name: 'Memory Modules (RAM)',
      type: 'Computer Hardware',
      description: 'Spare memory for server upgrades',
      model: 'DDR4-3200 ECC',
      serialNumber: '123ABC-456DEF-78901, 987CBA-FED012-34567',
      locationId: 10,
      purchaseDate: '2023-10-19',
      warranty: {
        startDate: '2023-10-19',
        endDate: '2025-10-18',
      },
      status: 'Active',
    },
    {
      id: 34,
      name: 'KVM Switch',
      type: 'Hardware',
      description: 'Allows control of multiple servers from one console',
      model: 'Black Box KVMSG-DP-4K',
      serialNumber: '012345-67890-FEDCBA',
      locationId: 10,
      purchaseDate: '2021-05-04',
      warranty: {
        startDate: '2021-05-04',
        endDate: '2023-05-03',
      },
      status: 'Needs Maintenance',
    },
    {
      id: 35,
      name: 'Patch Cables (Network)',
      type: 'Networking',
      description: 'Set of cables for connecting network devices',
      model: 'Cat6 Ethernet Patch Cable',
      serialNumber: 'N/A',
      locationId: 10,
      purchaseDate: '2024-01-18',
      warranty: {
        startDate: 'N/A',
        endDate: 'N/A',
      },
      status: 'Active',
    },
    {
      id: 36,
      name: 'Software - Backup & Recovery',
      type: 'License',
      description: 'Software for data backup and disaster recovery',
      version: '2024',
      licenseKey: 'N/A',
      assignedTo: 'IT Department',
      renewalDate: '2025-01-12',
      status: 'Active',
    },
    {
      id: 37,
      name: 'Docking Station (Laptop)',
      type: 'Hardware',
      description: 'Provides additional ports and connectivity for laptops',
      model: 'Dell Thunderbolt Dock WD19S',
      serialNumber: '34567-FEDCBA-01234',
      locationId: 10,
      purchaseDate: '2023-12-14',
      warranty: {
        startDate: '2023-12-14',
        endDate: '2025-12-13',
      },
      status: 'Active',
    },
    {
      id: 38,
      name: 'External Battery Pack',
      type: 'Power Supply',
      description: 'Portable battery for powering laptops on the go',
      model: 'Anker PowerCore 10000mAh',
      serialNumber: '78901-23456-FEDCB',
      locationId: 10,
      purchaseDate: '2024-02-09',
      warranty: {
        startDate: '2024-02-09',
        endDate: '2026-02-08',
      },
      status: 'Active',
    },
    {
      id: 39,
      name: 'Monitor (Spare)',
      type: 'Computer Hardware',
      description: 'Spare monitor for workstation replacements',
      model: 'HP EliteDisplay E243m',
      serialNumber: 'FEDCBA-34567-01234',
      locationId: 10,
      purchaseDate: '2022-08-23',
      warranty: {
        startDate: '2022-08-23',
        endDate: '2024-08-22',
      },
      status: 'Active',
    },
    {
      id: 40,
      name: 'Cleaning Supplies (Electronics)',
      type: 'Office Supplies',
      description: 'Cleaning wipes and compressed air for electronic devices',
      model: 'NA',
      serialNumber: 'NA',
      locationId: 10,
      purchaseDate: '2024-03-15',
      warranty: {
        startDate: 'NA',
        endDate: 'NA',
      },
      status: 'Active',
    },
  ],
  'Facilities Department': [
    {
      id: 17,
      name: 'Tool Kit - Basic',
      type: 'Office Supplies',
      description: 'Set of common tools for maintenance tasks',
      model: 'NA',
      serialNumber: 'N/A',
      location: 'Facilities Department',
      purchaseDate: '2023-08-21',
      warranty: {
        startDate: 'N/A',
        endDate: 'N/A',
      },
      status: 'Active',
    },
    {
      id: 41,
      name: 'First Aid Kit (Large)',
      type: 'Safety Equipment',
      description: 'Comprehensive kit for handling workplace injuries',
      model: 'NA',
      serialNumber: 'N/A',
      locationId: 12,
      purchaseDate: '2023-05-11',
      warranty: {
        startDate: 'N/A',
        endDate: 'N/A',
      },
      status: 'Active',
    },
    {
      id: 42,
      name: 'Fire Extinguisher (Portable)',
      type: 'Safety Equipment',
      description: 'Handheld fire extinguisher for small fires',
      model: 'ABC Dry Chemical',
      serialNumber: '98765-43210-FEDC',
      locationId: 12,
      purchaseDate: '2022-12-07',
      warranty: {
        startDate: '2022-12-07',
        endDate: '2026-12-06',
      },
      status: 'Active',
    },
    {
      id: 43,
      name: 'Tool Set (Basic)',
      type: 'Office Supplies',
      description: 'Set of common tools for maintenance tasks',
      model: 'NA',
      serialNumber: 'N/A',
      locationId: 12,
      purchaseDate: '2024-01-25',
      warranty: {
        startDate: 'N/A',
        endDate: 'N/A',
      },
      status: 'Active',
    },
    {
      id: 44,
      name: 'Cleaning Cart',
      type: 'Office Supplies',
      description: 'Cart with cleaning supplies for maintaining the office',
      model: 'NA',
      serialNumber: 'N/A',
      locationId: 12,
      purchaseDate: '2023-09-20',
      warranty: {
        startDate: 'N/A',
        endDate: 'N/A',
      },
      status: 'Active',
    },
    {
      id: 45,
      name: 'Vacuum Cleaner (Commercial)',
      type: 'Office Equipment',
      description: 'Powerful vacuum cleaner for cleaning carpets and floors',
      model: 'Hoover CH300 Series',
      serialNumber: '12345-67890-FEDC',
      locationId: 12,
      purchaseDate: '2021-03-14',
      warranty: {
        startDate: '2021-03-14',
        endDate: '2023-03-13',
      },
      status: 'Needs Replacement',
    },
  ],
  'IT Department - Network Rack': [
    {
      id: 18,
      name: 'Router',
      type: 'Networking',
      description: 'Provides internet access for the office network',
      model: 'Linksys Velop WHW3203',
      serialNumber: '7890-CBA9-FEDC',
      location: 'IT Department - Network Rack',
      purchaseDate: '2022-02-07',
      warranty: {
        startDate: '2022-02-07',
        endDate: '2024-02-06',
      },
      status: 'Active',
    },
  ],
  'Building B, Hallway near Exit': [
    {
      id: 19,
      name: 'Fire Extinguisher',
      type: 'Safety Equipment',
      description: 'Wall-mounted fire extinguisher for fire safety',
      model: 'ABC Dry Chemical',
      serialNumber: '5432-FEDC-1234',
      location: 'Building B, Hallway near Exit',
      purchaseDate: '2021-01-19',
      warranty: {
        startDate: 'N/A',
        endDate: '2026-01-18',
      },
      status: 'Active',
    },
  ],
  'Break Room - Kitchen Area': [
    {
      id: 20,
      name: 'Coffee Machine',
      type: 'Office Equipment',
      description: 'Brews coffee for employee refreshment',
      model: 'Keurig K-Supreme Plus Smart',
      serialNumber: '3210-FEDC-9876',
      location: 'Break Room - Kitchen Area',
      purchaseDate: '2023-05-18',
      warranty: {
        startDate: '2023-05-18',
        endDate: '2025-05-17',
      },
      status: 'Active',
    },
  ],
  'Multiple Locations (Restocked Regularly)': [
    {
      id: 22,
      name: 'First Aid Kit',
      type: 'Safety Equipment',
      description: 'Basic medical supplies for minor workplace injuries',
      model: 'NA',
      serialNumber: 'N/A',
      location: 'Multiple Locations (Restocked Regularly)',
      purchaseDate: '2024-02-10',
      warranty: {
        startDate: 'N/A',
        endDate: 'N/A',
      },
      status: 'Active',
    },
  ],
  'Company-Wide': [
    {
      id: 23,
      name: 'VoIP Phone System',
      type: 'Telecommunications',
      description: 'Provides business phone functionality over the internet',
      model: 'Cisco Business Phones 3300 Series',
      serialNumber: 'N/A',
      location: 'Company-Wide',
      purchaseDate: '2020-07-14',
      warranty: {
        startDate: '2020-07-14',
        endDate: '2023-07-13',
      },
      status: 'Needs Upgrade',
    },
  ],
  'Finance Department': [
    {
      id: 26,
      name: 'Scanner',
      type: 'Office Equipment',
      description: 'Multifunction device for scanning documents',
      model: 'Brother MFC-L3770DW',
      serialNumber: '9876-FEDC-3210',
      location: 'Finance Department',
      purchaseDate: '2022-04-12',
      warranty: {
        startDate: '2022-04-12',
        endDate: '2024-04-11',
      },
      status: 'Active',
    },
    {
      id: 46,
      name: 'Shredder (High-Security)',
      type: 'Office Equipment',
      description: 'Shredder for secure disposal of confidential documents',
      model: 'Fellowes Powershred 99MS',
      serialNumber: 'FEDC3210-5432-1234',
      locationId: 17,
      purchaseDate: '2022-04-19',
      warranty: {
        startDate: '2022-04-19',
        endDate: '2024-04-18',
      },
      status: 'Active',
    },
    {
      id: 47,
      name: 'Calculator (Financial)',
      type: 'Office Equipment',
      description: 'Advanced calculator for financial calculations',
      model: 'Texas Instruments BA II Plus',
      serialNumber: 'N/A',
      locationId: 17,
      purchaseDate: '2024-02-14',
      warranty: {
        startDate: 'N/A',
        endDate: 'N/A',
      },
      status: 'Active',
    },
    {
      id: 48,
      name: 'Accounting Software',
      type: 'License',
      description: 'Software for managing financial data and processes',
      version: '2024',
      licenseKey: 'N/A',
      assignedTo: 'Finance Department',
      renewalDate: '2025-07-10',
      status: 'Active',
    },
    {
      id: 49,
      name: 'Printer (Multifunction - Laser)',
      type: 'Office Equipment',
      description: 'Prints, scans, and copies documents',
      model: 'HP LaserJet Pro M404dn',
      serialNumber: '98765-43210-FEDC',
      locationId: 17,
      purchaseDate: '2023-11-21',
      warranty: {
        startDate: '2023-11-21',
        endDate: '2025-11-20',
      },
      status: 'Active',
    },
  ],
  'Building B, Floor 1 - Various cubicles': [
    {
      id: 27,
      name: 'Chair Mat',
      type: 'Office Supplies',
      description: 'Protects floor from office chair wear and tear',
      model: 'NA',
      serialNumber: 'N/A',
      location: 'Building B, Floor 1 - Various cubicles',
      purchaseDate: '2023-09-22',
      warranty: {
        startDate: 'N/A',
        endDate: 'N/A',
      },
      status: 'Active',
    },
  ],
  'Engineering Department': [
    {
      id: 30,
      name: '3D Printer',
      type: 'Hardware',
      description: 'Used for prototyping and creating physical models',
      model: 'Creality Ender 3 V2',
      serialNumber: 'FEDC3210-5432-1234',
      location: 'Engineering Department',
      purchaseDate: '2023-12-07',
      warranty: {
        startDate: '2023-12-07',
        endDate: '2025-12-06',
      },
      status: 'Active',
    },
    {
      id: 50,
      name: 'Workstation - Engineering Team',
      type: 'Computer',
      description: 'High-performance desktops for engineering software',
      model: 'Dell Precision 3660',
      serialNumber: 'ABCDEF-012345-67890',
      locationId: 20,
      purchaseDate: '2023-08-10',
      warranty: {
        startDate: '2023-08-10',
        endDate: '2025-08-09',
      },
      status: 'Active',
    },
    {
      id: 51,
      name: 'Software - CAD (Computer-Aided Design)',
      type: 'License',
      description: 'Software for creating 2D and 3D engineering designs',
      version: '2024',
      licenseKey: 'N/A',
      assignedTo: 'Engineering Department',
      renewalDate: '2025-05-19',
      status: 'Active',
    },
    {
      id: 52,
      name: 'Project Management Software (Engineering)',
      type: 'License',
      description: 'Software for managing engineering projects and tasks',
      version: 'Enterprise',
      licenseKey: 'N/A',
      assignedTo: 'Engineering Department',
      renewalDate: '2024-11-07',
      status: 'Active',
    },
    {
      id: 53,
      name: 'Whiteboard (Mobile)',
      type: 'Office Supplies',
      description: 'Rolling whiteboard for brainstorming and presentations',
      model: 'NA',
      serialNumber: 'NA',
      locationId: 20,
      purchaseDate: '2022-02-22',
      warranty: {
        startDate: 'NA',
        endDate: 'NA',
      },
      status: 'Active',
    },
    {
      id: 54,
      name: 'Prototyping Materials (3D Printing)',
      type: 'Consumables',
      description: 'Filament for 3D printer used in prototyping',
      model: 'PLA Filament (Various Colors)',
      serialNumber: 'NA',
      locationId: 20,
      purchaseDate: '2024-03-12',
      warranty: {
        startDate: 'NA',
        endDate: 'NA',
      },
      status: 'Active',
    },
    {
      id: 55,
      name: 'Safety Glasses',
      type: 'Safety Equipment',
      description: 'Eye protection for working in the engineering lab',
      model: 'NA',
      serialNumber: 'NA',
      locationId: 20,
      purchaseDate: '2024-02-10',
      warranty: {
        startDate: 'NA',
        endDate: 'NA',
      },
      status: 'Active',
    },
    {
      id: 56,
      name: 'Tool Set (Precision)',
      type: 'Office Supplies',
      description: 'Set of specialized tools for engineering tasks',
      model: 'NA',
      serialNumber: 'NA',
      locationId: 20,
      purchaseDate: '2023-06-14',
      warranty: {
        startDate: 'NA',
        endDate: 'NA',
      },
      status: 'Active',
    },
    {
      id: 57,
      name: 'Multimeter',
      type: 'Test Equipment',
      description: 'Tool for measuring electrical properties',
      model: 'Fluke 179',
      serialNumber: '12345-67890-FEDC',
      locationId: 20,
      purchaseDate: '2021-11-19',
      warranty: {
        startDate: '2021-11-19',
        endDate: '2023-11-18',
      },
      status: 'Needs Calibration',
    },
    {
      id: 58,
      name: 'Soldering Station',
      type: 'Test Equipment',
      description: 'Station for soldering electronic components',
      model: 'Yihua 936',
      serialNumber: '54321-01234-FEDC',
      locationId: 20,
      purchaseDate: '2022-09-21',
      warranty: {
        startDate: '2022-09-21',
        endDate: '2024-09-20',
      },
      status: 'Active',
    },
    {
      id: 59,
      name: 'Oscilloscope',
      type: 'Test Equipment',
      description: 'Tool for viewing electrical waveforms',
      model: 'Rigol DS1054Z',
      serialNumber: '98765-43210-FEDC',
      locationId: 20,
      purchaseDate: '2020-01-12',
      warranty: {
        startDate: '2020-01-12',
        endDate: '2023-01-11',
      },
      status: 'Needs Replacement',
    },
    {
      id: 60,
      name: 'Computer-Aided Manufacturing (CAM) Software',
      type: 'License',
      description:
        'Software for generating instructions for computer-controlled machines',
      version: '2023',
      licenseKey: 'N/A',
      assignedTo: 'Engineering Department',
      renewalDate: '2024-06-25',
      status: 'Active',
    },
  ],
};
